n = input('Digite algo:')
print('O tipo primitivo deste dado é: {} '.format(type(n)))
print('É numerico? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfa-numerico? {}'.format(n.isalnum()))
print('Está em minusculo? {}'.format(n.islower()))
print('Só tem espaço? {}'.format(n.isspace()))
print('É capitalizada (primieira letra maiuscula)? {}'.format(n.istitle()))
print('Está em maiúsculo? {}'.format(n.isupper()))
